# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tuUI0gqvWuqTzKbiTrHbxdoDS9vophgI
"""

import pandas as pd
import numpy as np

employee_data = {
    'Id': [1, 2, 3, 4],
    'Name': ['Pankaj', 'Meghna', 'David', 'Lisa'],
    'Role': ['CEO', np.nan, np.nan, 'np.nans'],
    'Salary': [100, 200, np.nan, np.nan]
}

df = pd.DataFrame(employee_data)

print("Initial DataFrame:")
print(df)

print("\nFirst 2 rows:")
print(df.head(2))

print("\nLast 2 rows:")
print(df.tail(2))

print("\nTotal null values:")
print(df.isnull().sum())

print("\nDataFrame Information:")
print(df.info())

df_rows_dropped = df.dropna()
print("\nDataFrame after dropping rows with null values:")
print(df_rows_dropped)

df_cols_dropped = df.dropna(axis=1)
print("\nDataFrame after dropping columns with null values:")
print(df_cols_dropped)

df['Salary'].fillna(300, inplace=True)
df['Role'].fillna('CEO', inplace=True)

print("\nUpdated DataFrame after filling null values:")
print(df)